name: Run Check CI check and tests

on:
   pull_request:
      branches: [dev]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run lint check
        run: ./gradlew lint

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: SonarQube check
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          args: > 
            - Dsonar.organization=alex-basanets
            - Dsonar.projectKey=Book-Trails
            - Dsonar.sources=src/main/kotlin
            - Dsonar.tests=src/test/kotlin
            - Dsonar.java.binaries=build